apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgAy0qjXvSyckj3z91vm6bar11uJxZHeYvGdoC7lhlq2U+Ay1pTnk0rU0EsS+xCo5sAaBaZz5c4yvBRI92gf0m8O9qHlXdYWG9Ak6V04mCKgkjwD4wShFXlbeRDGFT/nfCil2WNWD8P7ypFIf5WXHmaPX9VBPv1Cmow8xtSCbcuBNi837HiZu47d/rMagryXhu4HzhgO8C7SjRusmOu7YkgmauVDkX5w4DE7Xp9f+RVKqNVBRUGkoTdT+k5meec3xUdAXeiYIc5ypXmWtfuY5quIyEI90a1wQIDpAzyQb5WBsMvRoXKeWMBAOAWlWyOk7cDfkTQu4kDRRb3LcxPbGOYYu2HOF/iFVlfgJtMob8pNnRpJy+dEEStsH8LFfH/gNF6L5WCPJfGn8a1VL0lfsLMj2gR3PfVzpTzpmWnHze9UbGHcQ5MURHlxWqmyDvxxVouXq0jdM20xFXuaqkTVswoQ/3s5g9fOy3XTfu0pXUcB3FiVTNTm2z/i9r0ffRiTTPACDHTa4lMSRbMPO8u0dLWDbuKaRKMd3KkYW3475qY6rEyjZyafChhATT5V6sByyE9/FgwHbxRoboj3QT0d3fJiHg5gOurWIv/b0qrvEIreP92osPLTzDJ6je0zH25BH2phHo07hviIDWjYIrq6IDa1/qd9caAQ+zxz9rTRD3cwwopglzGdOUU36c/temZIGKhHwqXpIQ==
    username: AgC7IU1I6MrKp6fDwdh7+nlv/lNU5nPwizWvq4dqx8WGNqxJefdlXisb3R32aGNS7m/qv+ckiWbZbTt5ic1RfUWwPd5ppVkCwdxkXiJjKg/tcZ+xQojAKi3eMhVWKWrkLp/rTmeUDaC69q4KI2KJgP/NKb4OigaTVKVGwvHqLO5rwG4wrdV0UDs+nDaIIYSkNPnzLQcEpKQg+SYA1Bq60hd01d4eCNFTCxjMHyq5OCI4AejLZC5j/o/Tzvu0HtNG6LEd9yaUWz8aX3yE+/ztFqW0ZljCG0jQbGI3+MJFXTvC0O2fA4Un/A/vathNR3dBWK04/iCGc75oF5QKiM3KUCYTMZIkMBvZGHMENNH78edG1mAIYYHBXA+8gTYm+doKZm6L+6E1DYOr/QY3WTnuUtVQ5IB/h1rIqeX+r/HZCW01QmBsqmKvOYP7pj7CHwnITt5/vUJ1FJ1dXz3lZRQdb6SVGLby2zXYMXmPjNqJn4C//6Z+D/JGNaLqhmiVlIu1xBFAZRobw2OtLrAw1f4D4hABu9yIMNl7I+fwKwQopXoS7UYbnCHzQQKuPuVsUwzP7F8rFxD6/7dgc00IYq9vtMlD6YE/807/ksCnnB1VnhAxEr9prIsAnO1JEQ7ofNfkpp40UB9xHZXErYQ7IUySxkfhysxZJWQn6tC8fnkx2cndab7dWz6wCBS7TdSPNocd6AJonGAOTw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque

